server:
  host: 192.168.35.142
  port: 9090
  mode: debug # debug/release

mysql:
  # host: 45.119.55.22
  host: localhost
  port: 3306
  # user: miner
  user: root
  # password: "iRhPyszHSPC5LCXK"
  password: "3215"
  dbname: miner
  max_idle_conns: 10
  max_open_conns: 100

redis:
  host: localhost
  port: 7000
  password: "m3i2n1e0r"

jwt:
  secret: hello#:)
  expire: 24 # hours

log:
  level: debug
  filename: ./logs/server.log
  max_size: 100 # MB
  max_age: 30 # days
  max_backups: 10