services:
  miner:
    build: .
    ports:
      - "9090:9090"
    depends_on:
      - mysql
      - start-redis-cluster
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=10101
      - REDIS_HOST=redis-cluster-0
      - REDIS_PORT=7000
    volumes:
      - ./logs:/root/miner/logs
    networks:
      - backend
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=10101
      - MYSQL_DATABASE=miner
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend
  redis-cluster-nodes:
    build: ./redis-cluster
    volumes:
      - ./redis-cluster:/redis-cluster
  start-redis-cluster:
    image: bitnami/redis-cluster:latest
    volumes:
      - ./redis-cluster:/redis-cluster
    command: >
      sh -c "
      redis-cli --cluster create \
      127.0.0.1:7000 \
      127.0.0.1:7001 \
      127.0.0.1:7002 \
      127.0.0.1:7003 \
      127.0.0.1:7004 \
      127.0.0.1:7005 \
      --cluster-replicas 1 \
      -a m3i2n1e0r
      "
    depends_on:
      - redis-cluster-nodes
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  mysql_data: