info:
  contact: {}
paths:
  /user/{id}:
    get:
      consumes:
      - application/json
      description: 通过 ID 获取用户详细信息
      parameters:
      - description: 用户 ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: 获取用户信息
      tags:
      - 用户
swagger: "2.0"
